### ISSUE TITLE
Omnia_pick_merge v11 - KeyError: 'ir.values'

### ISSUE THREAD

**Issue by Capriatto** [OmniaSolutions/odooAddons#2]
I've got this error trying to install the Omnia_pick_merge module.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 572, in _tag_record
    model = self.env[rec_model]
  File "/odoo/odoo-server/odoo/api.py", line 761, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'ir.values'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "</usr/local/lib/python3.5/dist-packages/decorator.py:decorator-gen-42>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 543, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 572, in _tag_record
    model = self.env[rec_model]
  File "/odoo/odoo-server/odoo/api.py", line 761, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
odoo.tools.convert.ParseError: "ir.values" while parsing /odoo/odoo-server/addons/omnia_pick_merge/views/stock_picking.xml:23, near
<record id="value_action_server_merge_pick" model="ir.values">
            <field name="model_id" ref="stock.model_stock_picking"/>
            <field name="name">Merge</field>
            <field name="key2">client_action_multi</field>
            <field name="key">action</field>
            <field name="model">stock.picking</field>
            <field name="value" eval="'ir.actions.server,' + str(ref('action_server_merge_pick'))"/>
        </record>

**Comment by OmniaGit** [comment]
thanks for reporting the error we are fixin it
regards
Matteo

**Comment by OmniaGit** [comment]
Problem solved with this commit
https://github.com/OmniaSolutions/odooAddons/commit/647e14752242a9d953a030060bb6996d8f4cbb4a

odoo chenge on the road the ir.values that is no more supported
